### ISSUE TITLE
Integers are out of range

### ISSUE THREAD

**Issue by victor775** [acoustid/pg_acoustid#2]
Hi,

I am trying to use this extension to compare fingerprints generated with fpcalc (libchromaprint-tools). 
But the problem is what fpcalc generates an array of unsigned integers, like this 
`3666786748,3670972860,3662389148,2588444364,..`
and these extension functions require an array of signed integers. So, when I am trying to do:
`SELECT acoustid_extract_query('{3626576076,3670972860,3662389148}');`
Postgres says:
> ERROR:  value "3626576076" is out of range for type integer

Can you please advice how to handle this?

**Comment by lalinsky** [comment]
PostgreSQL doesn't support unsigned 32-bit integers, so you need to convert the output from fpcalc from unsigned to signed.

**Comment by trostli** [comment]
For anyone else that stumbles on this issue, I was able to overcome this without switching the output of fpcalc from unsigned to signed since I was already storing a bunch of fingerprints in the bigint format on postgres. I switched the functions arguments type to int8[] on my fork and it works as expected: 
https://github.com/trostli/pg_acoustid/commit/aab644fcbf9d553a27cc1635d091245beb43aaf4

Thank you for all the work you do @lalinsky !
